# job name is the name here, not the file name docker-image.yml
name: Docker Image CI

on:
  push:
    branches: [ "DISABLED_master", "sn50" ]
  pull_request:
    branches: [ "DISABLED_master", "sn50" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
